{{- $vault := default dict .Values.vault -}}
{{- if (default false $vault.enabled) }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: blacklist-telegram-token
  labels:
    {{- include "blacklist.labels" . | nindent 4 }}
spec:
  vaultAuthRef: {{ .Values.vault.auth.name }}
  type: kv-v2
  mount: {{ .Values.vault.telegram.mount }}
  path: {{ .Values.vault.telegram.path }}
  refreshAfter: {{ .Values.vault.telegram.refreshAfter }}
  destination:
    create: true
    overwrite: true
    name: {{ .Values.bot.runtimeSecrets.telegram.name }}
    transformation:
      excludes:
        - ".*"
      templates:
        {{ .Values.bot.runtimeSecrets.telegram.key }}:
          text: |
            {{`{{- get .Secrets "token" -}}`}}
{{- end }}
