FROM prometheuscommunity/postgres-exporter:v0.17.1

ARG YQ_VERSION=v4.44.3

USER root

WORKDIR /app

RUN mkdir -p /usr/local/bin

ADD --chmod=0755 --checksum=sha256:a2c097180dd884a8d50c956ee16a9cec070f30a7947cf4ebf87d5f36213e9ed7 \
  https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 \
  /usr/local/bin/yq

COPY infra/scripts/database-dsn.sh ./infra/scripts/database-dsn.sh

USER nobody
