{{- if (include "blacklist.botRuntimeSecretsEnabled" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blacklist.botConfigMapName" . }}
  labels:
    {{- include "blacklist.labels" . | nindent 4 }}
    app.kubernetes.io/component: bot
data:
  config.yaml: {{ .Files.Get "config/config.yaml" | quote }}
{{- end }}
