{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "blacklist.fullname" . }}-bot
  labels:
    {{- include "blacklist.labels" . | nindent 4 }}
    app.kubernetes.io/component: bot
  {{- if .Values.ingress.tls.enabled }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManager.clusterIssuer | quote }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}

  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}
  {{- end }}

  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "blacklist.fullname" . }}-bot
                port:
                  name: http
{{- end }}