apiVersion: v1
kind: Service
metadata:
  name: {{ include "blacklist.fullname" . }}-bot
  labels:
    {{- include "blacklist.labels" . | nindent 4 }}
    app.kubernetes.io/component: bot
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "blacklist.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: bot
  ports:
    - name: http
      port: {{ .Values.bot.containerPort }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.bot.metricsPort }}
      targetPort: metrics
      protocol: TCP
---
{{- if .Values.aimatcher.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blacklist.fullname" . }}-aimatcher
  labels:
    {{- include "blacklist.labels" . | nindent 4 }}
    app.kubernetes.io/component: aimatcher
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "blacklist.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: aimatcher
  ports:
    - name: http
      port: {{ .Values.aimatcher.containerPort }}
      targetPort: http
      protocol: TCP
{{- end }}
