{{- $vault := default dict .Values.vault -}}
{{- if (default false $vault.enabled) }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ .Values.vault.auth.name }}
  labels:
    {{- include "bastyle.labels" . | nindent 4 }}
spec:
  method: kubernetes
  mount: {{ .Values.vault.auth.mount }}
  kubernetes:
    role: {{ .Values.vault.auth.role }}
    serviceAccount: {{ include "bastyle.serviceAccountName" . }}
{{- end }}
