{{- $vault := default dict .Values.vault -}}
{{- if (default false $vault.enabled) }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: bastyle-postgres-dsn
  labels:
    {{- include "bastyle.labels" . | nindent 4 }}
spec:
  vaultAuthRef: {{ .Values.vault.auth.name }}
  mount: {{ .Values.vault.postgres.mount }}
  path: {{ .Values.vault.postgres.path }}
  renewalPercent: 67
  destination:
    create: true
    overwrite: true
    name: {{ .Values.bot.runtimeSecrets.database.name }}
    transformation:
      excludes:
        - ".*"
      templates:
        {{ .Values.bot.runtimeSecrets.database.key }}:
          text: |
            {{`{{- printf "%s://%s:%s@`}}{{ .Values.dependencies.postgresql.host }}:{{ .Values.dependencies.postgresql.port }}/{{ .Values.dependencies.postgresql.database }}?sslmode={{ .Values.vault.postgres.sslMode }}{{`" "postgres" (get .Secrets "username") (get .Secrets "password") -}}`}}
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ include "bastyle.fullname" . }}-bot
{{- end }}
