global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - "127.0.0.1:9090"

  - job_name: bastyle-bot
    metrics_path: /metrics
    static_configs:
      - targets:
          - "bastyle-blacklist:9090"

  - job_name: bastyle-aimatcher
    metrics_path: /metrics
    static_configs:
      - targets:
          - "bastyle-aimatcher:8080"

  - job_name: postgres-exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - "bastyle-postgres-exporter:9187"
