server:
  enabled: true
  ha:
    enabled: true
    replicas: 1
    raft:
      enabled: true
      setNodeId: true
  dataStorage:
    enabled: true
    size: 10Gi
  auditStorage:
    enabled: true
    size: 10Gi
  standalone:
    enabled: false
  dev:
    enabled: false

ui:
  enabled: true

injector:
  enabled: false
