{{- if .Values.rabbitmq.enabled }}
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ .Values.rabbitmq.clusterName }}
  labels:
    {{- include "bastyle.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  replicas: {{ .Values.rabbitmq.replicas }}
  image: {{ .Values.rabbitmq.image | quote }}

  persistence:
    storage: {{ .Values.rabbitmq.persistence.storage | quote }}
{{- end }}
