postgresql:
  enabled: true
  clusterName: "bastyle-postgresql"
  instances: 3
  imageName: "ghcr.io/cloudnative-pg/postgresql:16"
  storageSize: "10Gi"
  database: "bastyle"
  owner: "bastyle"
  existingSecret: "bastyle-postgresql"
  existingSecretUsernameKey: "username"
  existingSecretPasswordKey: "password"

migrations:
  enabled: true
  backoffLimit: 0
  dir: "/app/migrations"
  image:
    repository: "bastyle-migrations"
    tag: "local"

bot:
  replicaCount: 1
  image:
    repository: "bastyle-blacklist"
    tag: "local"
  containerPort: 8081
  configPath: "/etc/bastyle/config.yaml"

aimatcher:
  enabled: true
  image:
    repository: "bastyle-aimatcher"
    tag: "local"
  containerPort: 8080
  configPath: "/etc/bastyle/config.yaml"

service:
  type: ClusterIP
  aimatcher:
    port: 8080

configSecret:
  existingSecret: "bastyle-config"
  configKey: "config.yaml"

rabbitmq:
  enabled: true
  image: "rabbitmq:4.1.1-management"
  existingSecret: "bastyle-rabbitmq"
  existingSecretPasswordKey: "password"
  persistence:
    size: "5Gi"