{{- if .Values.postgresql.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.postgresql.clusterName }}
  labels:
    {{- include "bastyle.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  instances: {{ .Values.postgresql.instances }}
  imageName: {{ .Values.postgresql.imageName | quote }}

  bootstrap:
    initdb:
      database: {{ .Values.postgresql.database | quote }}
      owner: {{ .Values.postgresql.owner | quote }}
      secret:
        name: {{ .Values.postgresql.existingSecret | quote }}

  storage:
    size: {{ .Values.postgresql.storageSize | quote }}
{{- end }}
