{{- if (include "bastyle.legacyExternalConfigEnabled" .) }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "bastyle.configSecretName" . }}
  labels:
    {{- include "bastyle.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: bastyle-kubernetes-store
    kind: SecretStore
  target:
    name: {{ include "bastyle.configSecretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.configSecret.configKey }}
      remoteRef:
        key: "bastyle-config-source"
        property: {{ .Values.configSecret.configKey | quote }}
{{- end }}
